import { types } from "mobx-state-tree"

export const DishModel = types.model("Dish", {
  idMeal: types.identifier,
  strMeal: types.string,
  strCategory: types.optional(types.string, ""),
  strArea: types.maybeNull(types.string),
  strInstructions: types.string,
  strMealThumb: types.optional(types.string, ""),
  dateModified: types.maybeNull(types.string),
  ingredients: types.array(types.string),
  strCreativeCommonsConfirmed: types.maybeNull(types.string),
  strDrinkAlternate: types.maybeNull(types.string),
  strImageSource: types.maybeNull(types.string),
  strIngredient1: types.maybeNull(types.string),
  strIngredient2: types.maybeNull(types.string),
  strIngredient3: types.maybeNull(types.string),
  strIngredient4: types.maybeNull(types.string),
  strIngredient5: types.maybeNull(types.string),
  strIngredient6: types.maybeNull(types.string),
  strIngredient7: types.maybeNull(types.string),
  strIngredient8: types.maybeNull(types.string),
  strIngredient9: types.maybeNull(types.string),
  strIngredient10: types.maybeNull(types.string),
  strIngredient11: types.maybeNull(types.string),
  strIngredient12: types.maybeNull(types.string),
  strIngredient13: types.maybeNull(types.string),
  strIngredient14: types.maybeNull(types.string),
  strIngredient15: types.maybeNull(types.string),
  strIngredient16: types.maybeNull(types.string),
  strIngredient17: types.maybeNull(types.string),
  strIngredient18: types.maybeNull(types.string),
  strIngredient19: types.maybeNull(types.string),
  strIngredient20: types.maybeNull(types.string),
  strMeasure1: types.maybeNull(types.string),
  strMeasure2: types.maybeNull(types.string),
  strMeasure3: types.maybeNull(types.string),
  strMeasure4: types.maybeNull(types.string),
  strMeasure5: types.maybeNull(types.string),
  strMeasure6: types.maybeNull(types.string),
  strMeasure7: types.maybeNull(types.string),
  strMeasure8: types.maybeNull(types.string),
  strMeasure9: types.maybeNull(types.string),
  strMeasure10: types.maybeNull(types.string),
  strMeasure11: types.maybeNull(types.string),
  strMeasure12: types.maybeNull(types.string),
  strMeasure13: types.maybeNull(types.string),
  strMeasure14: types.maybeNull(types.string),
  strMeasure15: types.maybeNull(types.string),
  strMeasure16: types.maybeNull(types.string),
  strMeasure17: types.maybeNull(types.string),
  strMeasure18: types.maybeNull(types.string),
  strMeasure19: types.maybeNull(types.string),
  strMeasure20: types.maybeNull(types.string),
  strSource: types.maybeNull(types.string),
  strTags: types.maybeNull(types.string),
  strYoutube: types.string,
})
