name: Build React Native Android

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Add environment variables for Android build tools
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" > .env

      - name: Decode keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 -d > android/app/Production.keystore

      - name: Generate build number
        id: build-number
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease -PHOMEPLANNER_UPLOAD_STORE_FILE=Production.keystore -PHOMEPLANNER_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -PHOMEPLANNER_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }} -PHOMEPLANNER_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -PBUILD_NUMBER=${{ steps.build-number.outputs.timestamp }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v1.0.0 (${{ steps.build-number.outputs.timestamp }})"
          release_name: "The Meal App - v1.0.0"
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
